name: Demo CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  modules_preprocess:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit --ignore-scripts
      - name: Compress dependencies
        run: tar -cvf dependencies.tar node_modules
      - name: Upload node_modules artifact for later use
        uses: actions/upload-artifact@v3
        with:
          name: modules
          path: dependencies.tar
          retention-days: 1

  quality_assurance:
    name: Apply lint and test processes to the source code
    runs-on: ubuntu-latest
    needs: modules_preprocess
    timeout-minutes: 3
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: modules
      - name: Extract dependencies
        run: tar -xf dependencies.tar
      - name: Run ${{ matrix.task}}
        run: npm run ${{ matrix.task }}

  docker_build:
    name: Build the production docker image
    runs-on: ubuntu-latest
    needs: quality_assurance
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t greenict/demo-api
